---
- hosts: all:!localhost
  gather_facts: false
  any_errors_fatal: true
  roles:
    - ubuntu-ansible-req
    - ubuntu-add-luxoft-ca
    - ubuntu-docker-engine

- hosts: indypool
  roles:
    - indypool

- hosts: indyagents
  roles:
    - indyagents

- hosts: monolith
  roles:
    - monolith
