
spring:
  profiles: manufacture
server:
  port: 8081
node:
  address: 0.0.0.0
  rpcPort: 10002
  rpcUser: user1
  rpcPassword: test

---

spring:
  profiles: treatmentcenter
server:
  port: 8082
node:
  address: 0.0.0.0
  rpcPort: 10102
  rpcUser: user1
  rpcPassword: test
indy:
  trustedCredentialsIssuerDID: RRqP3Ze8x953G3chawJFJm